services:
  nginx:
    image: nginx:latest
    container_name: nginx
    platform: linux/amd64
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./www:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - php
      - db

  php:
    image: php:7.4-fpm
    container_name: php
    platform: linux/amd64
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "6001:80"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db_data:
